-- MySQL Script generated by MySQL Workbench
-- Sat May  5 09:27:14 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema cliniresearchdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cliniresearchdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cliniresearchdb` DEFAULT CHARACTER SET utf8 ;
USE `cliniresearchdb` ;

-- -----------------------------------------------------
-- Table `cliniresearchdb`.`Client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cliniresearchdb`.`Client` ;

CREATE TABLE IF NOT EXISTS `cliniresearchdb`.`Client` (
  `Client_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` TINYTEXT NOT NULL,
  `Adress` TINYTEXT NULL DEFAULT NULL,
  `Postal_Code` TINYTEXT NULL DEFAULT NULL,
  `City` TINYTEXT NULL DEFAULT NULL,
  `Country` TINYTEXT NULL DEFAULT NULL,
  `Contact_Person` TINYTEXT NULL DEFAULT NULL,
  `Invoice_info` TINYTEXT NULL DEFAULT NULL,
  `Kind_of_Client` TINYTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`Client_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cliniresearchdb`.`Project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cliniresearchdb`.`Project` ;

CREATE TABLE IF NOT EXISTS `cliniresearchdb`.`Project` (
  `Project_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Title` TINYTEXT NOT NULL,
  `Start_Date` DATE NULL,
  `End_Date` DATE NULL,
  PRIMARY KEY (`Project_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cliniresearchdb`.`Contract`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cliniresearchdb`.`Contract` ;

CREATE TABLE IF NOT EXISTS `cliniresearchdb`.`Contract` (
  `Contract_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Legal_Country` TINYTEXT NULL DEFAULT NULL,
  `Fee` DOUBLE NULL DEFAULT NULL,
  `Start_Date` DATE NULL DEFAULT NULL,
  `End_Date` DATE NULL DEFAULT NULL,
  `Client_ID` INT(11) NOT NULL,
  `Project_ID` INT(11) NOT NULL,
  PRIMARY KEY (`Contract_ID`),
  INDEX `fk_Client_ID_idx` (`Client_ID` ASC),
  INDEX `fk_Project_ID_idx` (`Project_ID` ASC),
  CONSTRAINT `fk_Client_Contract`
    FOREIGN KEY (`Client_ID`)
    REFERENCES `cliniresearchdb`.`Client` (`Client_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Project_Contract`
    FOREIGN KEY (`Project_ID`)
    REFERENCES `cliniresearchdb`.`Project` (`Project_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cliniresearchdb`.`CRA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cliniresearchdb`.`CRA` ;

CREATE TABLE IF NOT EXISTS `cliniresearchdb`.`CRA` (
  `CRA_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` TINYTEXT NOT NULL,
  `CV` TINYTEXT NULL,
  `Email` TINYTEXT NULL,
  `Phone1` TINYTEXT NULL,
  `Phone2` TINYTEXT NULL,
  PRIMARY KEY (`CRA_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cliniresearchdb`.`Hospital`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cliniresearchdb`.`Hospital` ;

CREATE TABLE IF NOT EXISTS `cliniresearchdb`.`Hospital` (
  `Hospital_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` TINYTEXT NOT NULL,
  `Adress` TINYTEXT NULL,
  `Postal_Code` TINYTEXT NULL,
  `City` TINYTEXT NULL,
  `Country` TINYTEXT NULL,
  `Central_Number` TINYTEXT NULL,
  PRIMARY KEY (`Hospital_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cliniresearchdb`.`Department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cliniresearchdb`.`Department` ;

CREATE TABLE IF NOT EXISTS `cliniresearchdb`.`Department` (
  `Department_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` TINYTEXT NOT NULL,
  `Email` TINYTEXT NULL,
  `Phone1` TINYTEXT NULL,
  `Hospital_ID` INT(11) NOT NULL,
  PRIMARY KEY (`Department_ID`),
  INDEX `fk_Hospital_ID_idx` (`Hospital_ID` ASC),
  CONSTRAINT `fk_Hospital_Department`
    FOREIGN KEY (`Hospital_ID`)
    REFERENCES `cliniresearchdb`.`Hospital` (`Hospital_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cliniresearchdb`.`Doctor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cliniresearchdb`.`Doctor` ;

CREATE TABLE IF NOT EXISTS `cliniresearchdb`.`Doctor` (
  `Doctor_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` TINYTEXT NOT NULL,
  `Email` TINYTEXT NULL,
  `Phone1` TINYTEXT NULL,
  `Phone2` TINYTEXT NULL,
  `Adress` TINYTEXT NULL,
  `Postal_Code` TINYTEXT NULL,
  `City` TINYTEXT NULL,
  `Country` TINYTEXT NULL,
  `Specialisation` TINYTEXT NULL,
  `CV` TINYTEXT NULL,
  PRIMARY KEY (`Doctor_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cliniresearchdb`.`Project_has_Doctor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cliniresearchdb`.`Project_has_Doctor` ;

CREATE TABLE IF NOT EXISTS `cliniresearchdb`.`Project_has_Doctor` (
  `Project_ID` INT(11) NOT NULL,
  `Doctor_ID` INT(11) NOT NULL,
  INDEX `fk_Doctor_ID_idx` (`Doctor_ID` ASC),
  INDEX `fk_Project_ID_idx` (`Project_ID` ASC),
  CONSTRAINT `fk_Project_Project_has_Doctor`
    FOREIGN KEY (`Project_ID`)
    REFERENCES `cliniresearchdb`.`Project` (`Project_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Doctor_Project_has_Doctor`
    FOREIGN KEY (`Doctor_ID`)
    REFERENCES `cliniresearchdb`.`Doctor` (`Doctor_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cliniresearchdb`.`Studycoordinator`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cliniresearchdb`.`StudyCoordinator` ;

CREATE TABLE IF NOT EXISTS `cliniresearchdb`.`StudyCoordinator` (
  `StudyCoordinator_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` TINYTEXT NOT NULL,
  `CV` TINYTEXT NULL,
  `Email` TINYTEXT NULL,
  `Phone1` TINYTEXT NULL,
  `Phone2` TINYTEXT NULL,
  `Specialisation` TINYTEXT NULL,
  PRIMARY KEY (`StudyCoordinator_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cliniresearchdb`.`Evaluation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cliniresearchdb`.`Evaluation` ;

CREATE TABLE IF NOT EXISTS `cliniresearchdb`.`Evaluation` (
  `Evaluation_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Date` DATE NOT NULL,
  `Feedback` TINYTEXT NULL,
  `Accuracy` TINYTEXT NULL,
  `Quality` TINYTEXT NULL,
  `Evaluation_Text` LONGTEXT NULL,
  `Label` TINYTEXT NULL,
  `StudyCoordinator_ID` INT(11) NULL,
  `Doctor_ID` INT(11) NULL,
  `CRA_ID` INT(11) NULL,
  PRIMARY KEY (`Evaluation_ID`),
  INDEX `fk_StudyCoordinator_ID_idx` (`StudyCoordinator_ID` ASC),
  INDEX `fk_Doctor_ID_idx` (`Doctor_ID` ASC),
  INDEX `fk_CRA_ID_idx` (`CRA_ID` ASC),
  CONSTRAINT `fk_StudyCoordinator_Evaluation`
    FOREIGN KEY (`StudyCoordinator_ID`)
    REFERENCES `cliniresearchdb`.`StudyCoordinator` (`StudyCoordinator_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Doctor_Evaluation`
    FOREIGN KEY (`Doctor_ID`)
    REFERENCES `cliniresearchdb`.`Doctor` (`Doctor_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CRA_Evaluation`
    FOREIGN KEY (`CRA_ID`)
    REFERENCES `cliniresearchdb`.`CRA` (`CRA_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cliniresearchdb`.`Doctor_has_Hospital`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cliniresearchdb`.`Doctor_has_Hospital` ;

CREATE TABLE IF NOT EXISTS `cliniresearchdb`.`Doctor_has_Hospital` (
  `Doctor_ID` INT(11) NOT NULL,
  `Hospital_ID` INT(11) NOT NULL,
  INDEX `fk_Hospital_ID_idx` (`Hospital_ID` ASC),
  INDEX `fk_Doctor_ID_idx` (`Doctor_ID` ASC),
  CONSTRAINT `fk_Hospital_Doctor_has_Hospital`
    FOREIGN KEY (`Hospital_ID`)
    REFERENCES `cliniresearchdb`.`Hospital` (`Hospital_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Doctor_Doctor_has_Hospital`
    FOREIGN KEY (`Doctor_ID`)
    REFERENCES `cliniresearchdb`.`Doctor` (`Doctor_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cliniresearchdb`.`Project_has_CRA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cliniresearchdb`.`Project_has_CRA` ;

CREATE TABLE IF NOT EXISTS `cliniresearchdb`.`Project_has_CRA` (
  `Project_ID` INT(11) NOT NULL,
  `CRA_ID` INT(11) NOT NULL,
  INDEX `fk_CRA_ID_idx` (`CRA_ID` ASC),
  INDEX `fk_Project_ID_idx` (`Project_ID` ASC),
  CONSTRAINT `fk_CRA_Project_has_CRA`
    FOREIGN KEY (`CRA_ID`)
    REFERENCES `cliniresearchdb`.`CRA` (`CRA_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Project_Project_has_CRA`
    FOREIGN KEY (`Project_ID`)
    REFERENCES `cliniresearchdb`.`Project` (`Project_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cliniresearchdb`.`ProjectManager`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cliniresearchdb`.`ProjectManager` ;

CREATE TABLE IF NOT EXISTS `cliniresearchdb`.`ProjectManager` (
  `ProjectManager_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` TINYTEXT NOT NULL,
  `CV` TINYTEXT NULL,
  `Email` TINYTEXT NULL,
  `Phone1` TINYTEXT NULL,
  `Phone2` TINYTEXT NULL,
  PRIMARY KEY (`ProjectManager_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cliniresearchdb`.`Project_has_ProjectManager`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cliniresearchdb`.`Project_has_ProjectManager` ;

CREATE TABLE IF NOT EXISTS `cliniresearchdb`.`Project_has_ProjectManager` (
  `Project_ID` INT(11) NOT NULL,
  `ProjectManager_ID` INT(11) NOT NULL,
  INDEX `fk_Project_ID_idx` (`Project_ID` ASC),
  INDEX `fk_ProjectManager_ID_idx` (`ProjectManager_ID` ASC),
  CONSTRAINT `fk_Project_Project_has_ProjectManager`
    FOREIGN KEY (`Project_ID`)
    REFERENCES `cliniresearchdb`.`Project` (`Project_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProjectManager_Project_has_ProjectManager`
    FOREIGN KEY (`ProjectManager_ID`)
    REFERENCES `cliniresearchdb`.`ProjectManager` (`ProjectManager_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cliniresearchdb`.`Studycoordinator_has_Doctor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cliniresearchdb`.`StudyCoordinator_has_Doctor` ;

CREATE TABLE IF NOT EXISTS `cliniresearchdb`.`StudyCoordinator_has_Doctor` (
  `StudyCoordinator_ID` INT(11) NOT NULL,
  `Doctor_ID` INT(11) NOT NULL,
  INDEX `fk_Doctor_ID_idx` (`Doctor_ID` ASC),
  INDEX `fk_StudyCoordinator_ID_idx` (`StudyCoordinator_ID` ASC),
  CONSTRAINT `fk_Doctor_StudyCoordinator_has_Doctor`
    FOREIGN KEY (`Doctor_ID`)
    REFERENCES `cliniresearchdb`.`Doctor` (`Doctor_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_StudyCoordinator_StudyCoordinator_has_Doctor`
    FOREIGN KEY (`StudyCoordinator_ID`)
    REFERENCES `cliniresearchdb`.`StudyCoordinator` (`StudyCoordinator_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cliniresearchdb`.`Project_has_Hospital`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cliniresearchdb`.`Project_has_Hospital` ;

CREATE TABLE IF NOT EXISTS `cliniresearchdb`.`Project_has_Hospital` (
  `Project_ID` INT(11) NOT NULL,
  `Hospital_ID` INT(11) NOT NULL,
  INDEX `fk_Hospital_ID_idx` (`Hospital_ID` ASC),
  INDEX `fk_Project_ID_idx` (`Project_ID` ASC),
  CONSTRAINT `fk_Project_Project_has_Hospital`
    FOREIGN KEY (`Project_ID`)
    REFERENCES `cliniresearchdb`.`Project` (`Project_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Hospital_Project_has_Hospital`
    FOREIGN KEY (`Hospital_ID`)
    REFERENCES `cliniresearchdb`.`Hospital` (`Hospital_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
