<%@ Page Title="" Language="C#" MasterPageFile="~/CliniresearchSite.Master" AutoEventWireup="true" CodeBehind="ClientPage.aspx.cs" Inherits="Presentation.Site.ClientSite" %>

<asp:Content ID="Head" ContentPlaceHolderID="Head" runat="server">
    <title>Clients</title>
</asp:Content>

<asp:Content ID="Header" ContentPlaceHolderID="Header" runat="server">
    <div class="headLeft"><p class="uppercase">Clients</p></div>
	<div class="headRight"><a href="../SiteEdit/ClientPageEdit.aspx"><i class="material-icons">create</i></a></div>
</asp:Content>

<asp:Content ID="Body" ContentPlaceHolderID="Body" runat="server">
    <asp:GridView ID="GridView" runat="server" AllowSorting="True" AutoGenerateDeleteButton="True" OnRowDeleting="GridView_RowDeleting" AutoGenerateColumns="False">
        <Columns>
            <asp:BoundField DataField="Client_ID" HeaderText="ClientID" HeaderStyle-CssClass="hideGridColumn" ItemStyle-CssClass="hideGridColumn"/>
            <asp:BoundField DataField="Name" HeaderText="Name"/>
            <asp:BoundField DataField="Adress" HeaderText="Adress"/>
            <asp:BoundField DataField="Postal_Code" HeaderText="Postal Code"/>
            <asp:BoundField DataField="City" HeaderText="City"/>
            <asp:BoundField DataField="Country" HeaderText="Counrty"/>
            <asp:BoundField DataField="Contact_Person" HeaderText="Contact Person"/>
            <asp:BoundField DataField="Invoice_Info" HeaderText="Invoice Info"/>
            <asp:BoundField DataField="Kind_of_Client" HeaderText="Kind of Client"/>
        </Columns>
	</asp:GridView>
</asp:Content>